export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  SET_COLLECTIONS: 'SET_COLLECTIONS',
  SELECTED_COLLECTION: 'SELECTED_COLLECTION',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SELECTED_CATEGORY: 'SELECTED_CATEGORY',
};
